#ifndef CUBEMAPFACES_H
#define CUBEMAPFACES_H

enum CubeMapFace 
{
	CUBE_MAP_FACE_LEFT = 0,
	CUBE_MAP_FACE_RIGHT,
	CUBE_MAP_FACE_UP,
	CUBE_MAP_FACE_DOWN,
	CUBE_MAP_FACE_FRONT,
	CUBE_MAP_FACE_BACK,
	CUBE_MAP_FACE_COUNT
};

#endif