#ifndef INPUTKEY_H
#define INPUTKEY_H

#include <SDL2/SDL.h>

enum InputKey
{
	/*
	 * Numeric Section
	*/

	RETURN = SDLK_RETURN,
	ESCAPE = SDLK_ESCAPE,
	BACKSPACE = SDLK_BACKSPACE,
	TAB = SDLK_TAB,
	SPACE = SDLK_SPACE,
	EXCLAIM = SDLK_EXCLAIM,
	QUOTEDBL = SDLK_QUOTEDBL,
	HASH = SDLK_HASH,
	PERCENT = SDLK_PERCENT,
	DOLLAR = SDLK_DOLLAR,
	AMPERSAND = SDLK_AMPERSAND,
	QUOTE = SDLK_QUOTE,
	LEFTPAREN = SDLK_LEFTPAREN,
	RIGHTPAREN = SDLK_RIGHTPAREN,
	ASTERISK = SDLK_ASTERISK,
	PLUS = SDLK_PLUS,
	COMMA = SDLK_COMMA,
	MINUS = SDLK_MINUS,
	PERIOD = SDLK_PERIOD,
	SLASH = SDLK_SLASH,
	ALPHA_0 = SDLK_0,
	ALPHA_1 = SDLK_1,
	ALPHA_2 = SDLK_2,
	ALPHA_3 = SDLK_3,
	ALPHA_4 = SDLK_4,
	ALPHA_5 = SDLK_5,
	ALPHA_6 = SDLK_6,
	ALPHA_7 = SDLK_7,
	ALPHA_8 = SDLK_8,
	ALPHA_9 = SDLK_9,
	COLON = SDLK_COLON,
	SEMICOLON = SDLK_SEMICOLON,
	LESS = SDLK_LESS,
	EQUALS = SDLK_EQUALS,
	GREATER = SDLK_GREATER,
	QUESTION = SDLK_QUESTION,
	AT = SDLK_AT,
	LEFTBRACKET = SDLK_LEFTBRACKET,
	BACKSLASH = SDLK_BACKSLASH,
	RIGHTBRACKET = SDLK_RIGHTBRACKET,
	CARET = SDLK_CARET,
	UNDERSCORE = SDLK_UNDERSCORE,
	BACKQUOTE = SDLK_BACKQUOTE,

	/*
	 * Alpha Section
	*/

	A = SDLK_a,
	B = SDLK_b,
	C = SDLK_c,
	D = SDLK_d,
	E = SDLK_e,
	F = SDLK_f,
	G = SDLK_g,
	H = SDLK_h,
	I = SDLK_i,
	J = SDLK_j,
	K = SDLK_k,
	L = SDLK_l,
	M = SDLK_m,
	N = SDLK_n,
	O = SDLK_o,
	P = SDLK_p,
	Q = SDLK_q,
	R = SDLK_r,
	S = SDLK_s,
	T = SDLK_t,
	U = SDLK_u,
	V = SDLK_v,
	W = SDLK_w,
	X = SDLK_x,
	Y = SDLK_y,
	Z = SDLK_z,
	CAPSLOCK = SDLK_CAPSLOCK,

	/*
	 * Function Keys
	*/

	F1 = SDLK_F1,
	F2 = SDLK_F2,
	F3 = SDLK_F3,
	F4 = SDLK_F4,
	F5 = SDLK_F5,
	F6 = SDLK_F6,
	F7 = SDLK_F7,
	F8 = SDLK_F8,
	F9 = SDLK_F9,
	F10 = SDLK_F10,
	F11 = SDLK_F11,
	F12 = SDLK_F12,

	/*
	 * Navigation Section
	*/

	PRINTSCREEN = SDLK_PRINTSCREEN,
	SCROLLLOCK = SDLK_SCROLLLOCK,
	PAUSE = SDLK_PAUSE,
	INSERT = SDLK_INSERT,
	HOME = SDLK_HOME,
	PAGEUP = SDLK_PAGEUP,
	DELETE = SDLK_DELETE,
	END = SDLK_END,
	PAGEDOWN = SDLK_PAGEDOWN,
	RIGHT = SDLK_RIGHT,
	LEFT = SDLK_LEFT,
	DOWN = SDLK_DOWN,
	UP = SDLK_UP,

	/*
	 * Keypad Section
	*/

	NUMLOCKCLEAR = SDLK_NUMLOCKCLEAR,
	KEYPAD_DIVIDE = SDLK_KP_DIVIDE,
	KEYPAD_MULTIPLY = SDLK_KP_MULTIPLY,
	KEYPAD_MINUS = SDLK_KP_MINUS,
	KEYPAD_PLUS = SDLK_KP_PLUS,
	KEYPAD_ENTER = SDLK_KP_ENTER,
	KEYPAD_1 = SDLK_KP_1,
	KEYPAD_2 = SDLK_KP_2,
	KEYPAD_3 = SDLK_KP_3,
	KEYPAD_4 = SDLK_KP_4,
	KEYPAD_5 = SDLK_KP_5,
	KEYPAD_6 = SDLK_KP_6,
	KEYPAD_7 = SDLK_KP_7,
	KEYPAD_8 = SDLK_KP_8,
	KEYPAD_9 = SDLK_KP_9,
	KEYPAD_0 = SDLK_KP_0,
	KEYPAD_PERIOD = SDLK_KP_PERIOD,

	/*
	 * Miscellaneous Section
	*/

	APPLICATION = SDLK_APPLICATION,
	POWER = SDLK_POWER,
	F13 = SDLK_F13,
	F14 = SDLK_F14,
	F15 = SDLK_F15,
	F16 = SDLK_F16,
	F17 = SDLK_F17,
	F18 = SDLK_F18,
	F19 = SDLK_F19,
	F20 = SDLK_F20,
	F21 = SDLK_F21,
	F22 = SDLK_F22,
	F23 = SDLK_F23,
	F24 = SDLK_F24,
	MENU = SDLK_MENU,
	SELECT = SDLK_SELECT,
	STOP = SDLK_STOP,
	UNDO = SDLK_UNDO,
	CUT = SDLK_CUT,
	COPY = SDLK_COPY,
	PASTE = SDLK_PASTE,
	FIND = SDLK_FIND,
	MUTE = SDLK_MUTE,
	VOLUMEUP = SDLK_VOLUMEUP,
	VOLUMEDOWN = SDLK_VOLUMEDOWN,
	SLEEP = SDLK_SLEEP,

	/*
	 * Key Mode Section
	*/

	LCTRL = SDLK_LCTRL,
	LSHIFT = SDLK_LSHIFT,
	LALT = SDLK_LALT,
	LGUI = SDLK_LGUI,
	RCTRL = SDLK_RCTRL,
	RSHIFT = SDLK_RSHIFT,
	RALT = SDLK_RALT,
	RGUI = SDLK_RGUI,
	MODE = SDLK_MODE,

};

#endif