#ifndef CURSORTYPE_H
#define CURSORTYPE_H

#include <SDL2/SDL.h>

enum CursorType
{
	CURSOR_TYPE_ARROW = SDL_SYSTEM_CURSOR_ARROW,
	CURSOR_TYPE_IBEAM = SDL_SYSTEM_CURSOR_IBEAM,
	CURSOR_TYPE_WAIT = SDL_SYSTEM_CURSOR_WAIT,
	CURSOR_CROSSHAIR = SDL_SYSTEM_CURSOR_CROSSHAIR,
	CURSOR_TYPE_WAITARROW = SDL_SYSTEM_CURSOR_WAITARROW,
	CURSOR_TYPE_SIZENWSE = SDL_SYSTEM_CURSOR_SIZENWSE,
	CURSOR_TYPE_SIZENESW = SDL_SYSTEM_CURSOR_SIZENESW,
	CURSOR_TYPE_SIZEWE = SDL_SYSTEM_CURSOR_SIZEWE,
	CURSOR_TYPE_SIZENS = SDL_SYSTEM_CURSOR_SIZENS,
	CURSOR_TYPE_SIZEALL = SDL_SYSTEM_CURSOR_SIZEALL,
	CURSOR_TYPE_NO = SDL_SYSTEM_CURSOR_NO,
	CURSOR_TYPE_HAND = SDL_SYSTEM_CURSOR_HAND,
	CURSOR_TYPE_COUNT = SDL_NUM_SYSTEM_CURSORS
};

#endif